# This is a basic workflow to scan all pushes for patterns that suggest secrets /passwords
# it makes use of: https://github.com/marketplace/actions/trufflehog-check

name: secret-scan

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: UnicornGlobal/trufflehog-actions-scan@v1.0.0
      with:
        branch: ${{ github.head_ref }}
